# Generated by Django 5.1 on 2024-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
